### ISSUE TITLE
Dependency

### ISSUE THREAD

**Issue by Riz-waan** [AlonsoK28/xlsx-load-node#1]
Hi, I am the author of the node module xlsx-node. I believe I might have done something to break the module while trying to update some node modules. Would you be able to take a look at it and let me know?

**Comment by AlonsoK28** [comment]
> Hi, I am the author of the node module xlsx-node. I believe I might have done something to break the module while trying to update some node modules. Would you be able to take a look at it and let me know?

Thank you very much friend for all

Let me see what I can do
